"""Fixture configuration for the synthetic corridor: markings, contexts,
schemas, mappings, pipelines, workshop, staleness policy, clock helpers.
Data only — no behavior."""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from curunir_operational.access import AccessContext, Marking

T0 = "2026-03-01T06:00:00+00:00"


def at(hours: float) -> str:
    return (datetime.fromisoformat(T0) + timedelta(hours=hours)).astimezone(timezone.utc).isoformat()


BASE_MARKING = Marking(owning_authority="CIVDEF-AUTH", releasability=("CORRIDOR-OPS",))
RESTRICTED_MARKING = Marking(owning_authority="CIVDEF-AUTH", compartments=("SENSITIVE-INFRA",),
                             releasability=("CORRIDOR-OPS",), min_role="ANALYST")

CONTEXTS = {
    "high": AccessContext("ctx-high", "analyst-vale", "HUMAN", ("ANALYST", "SUPERVISOR"),
                          ("SENSITIVE-INFRA",), ("CORRIDOR-OPS",), "CIVDEF-AUTH"),
    "low": AccessContext("ctx-low", "liaison-brenn", "HUMAN", ("OBSERVER",),
                         (), ("CORRIDOR-OPS",), "PARTNER-RELIEF-ORG"),
    "rules": AccessContext("ctx-rules", "rule-engine", "SERVICE", ("ANALYST",),
                           ("SENSITIVE-INFRA",), ("CORRIDOR-OPS",), "CIVDEF-AUTH"),
}

STALENESS_HOURS = {"RESOURCE_STOCK": 36.0, "OBSERVATION": 48.0, "INFRASTRUCTURE": 96.0,
                   "ROUTE": 96.0, "MOVEMENT": 48.0}

SCHEMAS = [
    {"schema_id": "corridor-infrastructure", "version": "1.0", "media_type": "application/geo+json",
     "payload_kind": "geojson", "description": "registry export of corridor facilities",
     "fields": {"infra_id": {"type": "string", "required": True},
                "name": {"type": "string", "required": True},
                "kind": {"type": "string", "required": True,
                         "enum": ["depot", "bridge", "substation"]},
                "status": {"type": "string", "required": True},
                "effective_time": {"type": "string", "required": True, "format": "iso-datetime"}}},
    {"schema_id": "corridor-route", "version": "1.0", "media_type": "application/geo+json",
     "payload_kind": "geojson", "description": "registry export of corridor routes",
     "fields": {"route_id": {"type": "string", "required": True},
                "name": {"type": "string", "required": True},
                "crosses_ref": {"type": "string", "required": False},
                "alternate_ref": {"type": "string", "required": False},
                "effective_time": {"type": "string", "required": True, "format": "iso-datetime"}}},
    {"schema_id": "stock-report", "version": "1.0", "media_type": "text/csv", "payload_kind": "rows",
     "description": "depot stock levels",
     "fields": {"stock_id": {"type": "string", "required": True},
                "depot_ref": {"type": "string", "required": True},
                "commodity": {"type": "string", "required": True, "enum": ["fuel", "medical", "repair"]},
                "quantity": {"type": "number", "required": True},
                "unit": {"type": "string", "required": True},
                "report_time": {"type": "string", "required": True, "format": "iso-datetime"}}},
    {"schema_id": "movement-plan", "version": "1.0", "media_type": "application/json", "payload_kind": "document",
     "description": "planned or updated civil-defence movement",
     "fields": {"movement_id": {"type": "string", "required": True},
                "from_ref": {"type": "string", "required": True},
                "to_ref": {"type": "string", "required": True},
                "route_ref": {"type": "string", "required": True},
                "cargo": {"type": "string", "required": True},
                "status": {"type": "string", "required": True},
                "depart_time": {"type": "string", "required": True, "format": "iso-datetime"},
                "effective_time": {"type": "string", "required": True, "format": "iso-datetime"}}},
    {"schema_id": "field-observation", "version": "1.0", "media_type": "application/json", "payload_kind": "document",
     "description": "sensor-like or bulletin observation about corridor objects",
     "fields": {"report_id": {"type": "string", "required": True},
                "subject_ref": {"type": "string", "required": True},
                "subject_kind": {"type": "string", "required": True, "enum": ["infrastructure", "route"]},
                "reported_status": {"type": "string", "required": True},
                "detail": {"type": "string", "required": False},
                "lon": {"type": "number", "required": False},
                "lat": {"type": "number", "required": False},
                "observed_time": {"type": "string", "required": True, "format": "iso-datetime"},
                "corrects_report": {"type": "string", "required": False}}},
    {"schema_id": "movement-sighting", "version": "1.0", "media_type": "application/json", "payload_kind": "document",
     "description": "reported sighting of a vehicle group",
     "fields": {"sighting_id": {"type": "string", "required": True},
                "movement_ref": {"type": "string", "required": False},
                "vehicle_count": {"type": "integer", "required": False},
                "cargo": {"type": "string", "required": False},
                "lon": {"type": "number", "required": True},
                "lat": {"type": "number", "required": True},
                "observed_time": {"type": "string", "required": True, "format": "iso-datetime"}}},
    {"schema_id": "argus-evidence", "version": "1.0",
     "media_type": "application/vnd.curunir.argus-evidence+json", "payload_kind": "document",
     "description": "ARGUS Source Intelligence evidence bundle (adapter format)",
     "fields": {"source_object": {"type": "object", "required": True},
                "document": {"type": "object", "required": True},
                "assertion": {"type": "object", "required": True},
                "admission": {"type": "object", "required": False},
                "identity": {"type": "object", "required": False},
                "source_relationships": {"type": "array", "required": False}}},
]

MAPPINGS = [
    {"mapping_id": "infra-map", "version": "1.0", "input_schema_id": "corridor-infrastructure",
     "input_schema_version": "1.0", "output_object_type": "INFRASTRUCTURE",
     "entries": [
         {"source_field": "infra_id", "target": "external_id"},
         {"source_field": "name", "target": "label"},
         {"source_field": "kind", "target": "attributes.kind"},
         {"source_field": "status", "target": "attributes.status"},
         {"source_field": "effective_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "effective_time", "target": "source_time", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.95, "geospatial_precision": "REGISTRY_SURVEY"}},
    {"mapping_id": "route-map", "version": "1.0", "input_schema_id": "corridor-route",
     "input_schema_version": "1.0", "output_object_type": "ROUTE",
     "entries": [
         {"source_field": "route_id", "target": "external_id"},
         {"source_field": "name", "target": "label"},
         {"source_field": "crosses_ref", "target": "attributes.crosses_ref", "on_missing": "SKIP"},
         {"source_field": "alternate_ref", "target": "attributes.alternate_ref", "on_missing": "SKIP"},
         {"source_field": "effective_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "effective_time", "target": "source_time", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.95}},
    {"mapping_id": "stock-map", "version": "1.0", "input_schema_id": "stock-report",
     "input_schema_version": "1.0", "output_object_type": "RESOURCE_STOCK",
     "entries": [
         {"source_field": "stock_id", "target": "external_id"},
         {"source_field": "depot_ref", "target": "attributes.depot_ref"},
         {"source_field": "commodity", "target": "attributes.commodity"},
         {"source_field": "quantity", "target": "attributes.quantity", "transform": "to_number"},
         {"source_field": "unit", "target": "attributes.unit"},
         {"source_field": "report_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "report_time", "target": "source_time", "transform": "iso_time"}],
     "lossy_operations": ["origin system rounds quantities to reporting units"],
     "quality_effects": {"mapping_confidence": 0.9}},
    {"mapping_id": "movement-map", "version": "1.0", "input_schema_id": "movement-plan",
     "input_schema_version": "1.0", "output_object_type": "MOVEMENT",
     "entries": [
         {"source_field": "movement_id", "target": "external_id"},
         {"source_field": "movement_id", "target": "attributes.movement_ref"},
         {"source_field": "from_ref", "target": "attributes.from_ref"},
         {"source_field": "to_ref", "target": "attributes.to_ref"},
         {"source_field": "route_ref", "target": "attributes.route_ref"},
         {"source_field": "cargo", "target": "attributes.cargo"},
         {"source_field": "status", "target": "attributes.status"},
         {"source_field": "depart_time", "target": "attributes.depart_time", "transform": "iso_time"},
         {"source_field": "effective_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "effective_time", "target": "source_time", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.95}},
    {"mapping_id": "observation-map", "version": "1.0", "input_schema_id": "field-observation",
     "input_schema_version": "1.0", "output_object_type": "OBSERVATION",
     "entries": [
         {"source_field": "report_id", "target": "external_id"},
         {"source_field": "subject_ref", "target": "attributes.subject_ref"},
         {"source_field": "subject_kind", "target": "attributes.subject_kind"},
         {"source_field": "reported_status", "target": "attributes.reported_status"},
         {"source_field": "detail", "target": "attributes.detail", "on_missing": "SKIP"},
         {"source_field": "corrects_report", "target": "attributes.corrects_report", "on_missing": "SKIP"},
         {"source_field": "observed_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "observed_time", "target": "source_time", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.85}},
    {"mapping_id": "sighting-map", "version": "1.0", "input_schema_id": "movement-sighting",
     "input_schema_version": "1.0", "output_object_type": "MOVEMENT",
     "entries": [
         {"source_field": "sighting_id", "target": "external_id"},
         {"source_field": "movement_ref", "target": "attributes.movement_ref", "on_missing": "UNKNOWN"},
         {"source_field": "vehicle_count", "target": "attributes.vehicle_count", "on_missing": "UNKNOWN"},
         {"source_field": "cargo", "target": "attributes.cargo", "on_missing": "UNKNOWN"},
         {"source_field": "observed_time", "target": "valid_from", "transform": "iso_time"},
         {"source_field": "observed_time", "target": "source_time", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.6, "identity_confidence": "UNKNOWN"}},
    {"mapping_id": "evidence-map", "version": "1.0", "input_schema_id": "argus-evidence",
     "input_schema_version": "1.0", "output_object_type": "OBSERVATION",
     "entries": [
         {"source_field": "assertion_id", "target": "external_id"},
         {"source_field": "subject_ref", "target": "attributes.subject_ref"},
         {"source_field": "reported_status", "target": "attributes.reported_status"},
         {"source_field": "summary", "target": "attributes.detail", "on_missing": "SKIP"},
         {"source_field": "report_time", "target": "valid_from", "transform": "iso_time"}],
     "quality_effects": {"mapping_confidence": 0.8}},
]

PIPELINES = [
    {"pipeline_id": "infrastructure-status", "version": "1.0", "connector_id": "conn-registry-infra",
     "connector_kind": "geojson", "schema_id": "corridor-infrastructure", "schema_version": "1.0",
     "mode": "direct_state", "unit": "features",
     "object": {"object_type": "INFRASTRUCTURE", "id_prefix": "infra-", "external_system": "CORRIDOR-REGISTRY",
                "external_id_field": "infra_id", "epistemic_default": "REPORTED"},
     "mappings": [{"mapping_id": "infra-map", "version": "1.0"}],
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "route-registry", "version": "1.0", "connector_id": "conn-registry-route",
     "connector_kind": "geojson", "schema_id": "corridor-route", "schema_version": "1.0",
     "mode": "direct_state", "unit": "features",
     "object": {"object_type": "ROUTE", "id_prefix": "route-", "external_system": "CORRIDOR-REGISTRY",
                "external_id_field": "route_id", "epistemic_default": "REPORTED"},
     "mappings": [{"mapping_id": "route-map", "version": "1.0"}],
     "relationships": [
         {"relation_type": "DEPENDS_ON", "target_field": "crosses_ref", "target_prefix": "infra-", "direction": "OUT"},
         {"relation_type": "ALTERNATE_OF", "target_field": "alternate_ref", "target_prefix": "route-", "direction": "OUT"}],
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "logistics-stock", "version": "1.0", "connector_id": "conn-logsys-stock",
     "connector_kind": "csv", "schema_id": "stock-report", "schema_version": "1.0",
     "mode": "direct_state", "unit": "rows",
     "object": {"object_type": "RESOURCE_STOCK", "id_prefix": "stock-", "external_system": "LOGSYS",
                "external_id_field": "stock_id", "epistemic_default": "REPORTED"},
     "mappings": [{"mapping_id": "stock-map", "version": "1.0"}],
     "relationships": [
         {"relation_type": "LOCATED_AT", "target_field": "depot_ref", "target_prefix": "infra-", "direction": "OUT"}],
     "marking": BASE_MARKING.to_record()},
    # Dedupe on content: a new plan for the same movement is new state, so
    # only a byte-identical resend counts as a duplicate.
    {"pipeline_id": "movement-plan", "version": "1.0", "connector_id": "conn-moveplan",
     "connector_kind": "json", "schema_id": "movement-plan",
     "schema_version": "1.0", "mode": "direct_state", "unit": "document",
     "object": {"object_type": "MOVEMENT", "id_prefix": "mv-", "external_system": "MOVEPLAN",
                "external_id_field": "movement_id", "epistemic_default": "PLANNED"},
     "mappings": [{"mapping_id": "movement-map", "version": "1.0"}],
     "relationships": [
         {"relation_type": "PLANNED_FOR", "target_field": "route_ref", "target_prefix": "route-", "direction": "OUT"}],
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "field-observations", "version": "1.0", "connector_id": "conn-fieldnet",
     "connector_kind": "json", "event_id_field": "report_id", "schema_id": "field-observation",
     "schema_version": "1.0", "mode": "observation", "unit": "document",
     "object": {"object_type": "OBSERVATION", "id_prefix": "obs-", "external_system": "FIELDNET",
                "external_id_field": "report_id", "epistemic_default": "OBSERVED",
                "point_fields": {"lon": "lon", "lat": "lat"}},
     "mappings": [{"mapping_id": "observation-map", "version": "1.0"}],
     "observation": {"target_field": "subject_ref", "prefix_map_field": "subject_kind",
                     "prefix_map": {"infrastructure": "infra-", "route": "route-"}},
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "civdef-bulletins", "version": "1.0", "connector_id": "conn-civdef",
     "connector_kind": "json", "schema_id": "field-observation",
     "schema_version": "1.0", "mode": "observation", "unit": "document",
     "object": {"object_type": "OBSERVATION", "id_prefix": "obs-", "external_system": "CIVDEF-BULLETIN",
                "external_id_field": "report_id", "epistemic_default": "REPORTED"},
     "mappings": [{"mapping_id": "observation-map", "version": "1.0"}],
     "observation": {"target_field": "subject_ref", "prefix_map_field": "subject_kind",
                     "prefix_map": {"infrastructure": "infra-", "route": "route-"}},
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "movement-sightings", "version": "1.0", "connector_id": "conn-fieldnet-sightings",
     "connector_kind": "json", "event_id_field": "sighting_id", "schema_id": "movement-sighting",
     "schema_version": "1.0", "mode": "direct_state", "unit": "document",
     "object": {"object_type": "MOVEMENT", "id_prefix": "mvobs-", "external_system": "FIELDNET",
                "external_id_field": "sighting_id", "epistemic_default": "REPORTED",
                "point_fields": {"lon": "lon", "lat": "lat"},
                "external_refs_identity_bearing": False},
     "mappings": [{"mapping_id": "sighting-map", "version": "1.0"}],
     "marking": BASE_MARKING.to_record()},
    {"pipeline_id": "argus-evidence-observations", "version": "1.0", "connector_id": "conn-argus",
     "connector_kind": "argus_evidence", "schema_id": "argus-evidence", "schema_version": "1.0",
     "mode": "evidence_observation", "unit": "document",
     "object": {"object_type": "OBSERVATION", "id_prefix": "obs-", "external_system": "ARGUS-SI",
                "external_id_field": "assertion_id", "epistemic_default": "EXTRACTED"},
     "mappings": [{"mapping_id": "evidence-map", "version": "1.0"}],
     "observation": {"target_field": "subject_ref", "target_prefix": "infra-"},
     "marking": BASE_MARKING.to_record()},
]

WORKSHOP = {
    "workshop_id": "SHARED_LOGISTICS_VISIBILITY_WORKBENCH_V1", "version": "1.0",
    "purpose": "Shared logistics visibility for the synthetic Vessia relief corridor",
    "object_types": ["INFRASTRUCTURE", "ROUTE", "RESOURCE_STOCK", "MOVEMENT", "OBSERVATION"],
    "relationship_types": ["LOCATED_AT", "DEPENDS_ON", "PLANNED_FOR", "ALTERNATE_OF", "REPORTS_ON",
                           "CONFLICTS_WITH", "POSSIBLY_SAME_AS", "SAME_AS"],
    "filters": [],
    "tables": [
        {"table_id": "stock", "title": "Resource stock", "object_type": "RESOURCE_STOCK",
         "columns": [{"header": "id", "path": "object_id"},
                     {"header": "depot", "path": "attributes.depot_ref"},
                     {"header": "commodity", "path": "attributes.commodity"},
                     {"header": "quantity", "path": "attributes.quantity"},
                     {"header": "unit", "path": "attributes.unit"},
                     {"header": "state", "path": "epistemic_state"},
                     {"header": "freshness", "path": "freshness.state"}],
         "sort_by": "object_id"},
        {"table_id": "infrastructure", "title": "Infrastructure", "object_type": "INFRASTRUCTURE",
         "columns": [{"header": "id", "path": "object_id"},
                     {"header": "kind", "path": "attributes.kind"},
                     {"header": "status", "path": "attributes.status"},
                     {"header": "state", "path": "epistemic_state"},
                     {"header": "quality", "path": "quality_summary.state"}],
         "sort_by": "object_id"},
        {"table_id": "movements", "title": "Movements", "object_type": "MOVEMENT",
         "columns": [{"header": "id", "path": "object_id"},
                     {"header": "cargo", "path": "attributes.cargo"},
                     {"header": "route", "path": "attributes.route_ref"},
                     {"header": "status", "path": "attributes.status"},
                     {"header": "state", "path": "epistemic_state"}],
         "sort_by": "object_id"}],
    "map_layers": [
        {"layer_id": "infrastructure", "title": "Facilities", "object_types": ["INFRASTRUCTURE"],
         "geometry_kinds": ["POINT"]},
        {"layer_id": "routes", "title": "Routes", "object_types": ["ROUTE"], "geometry_kinds": ["LINESTRING"]},
        {"layer_id": "observations", "title": "Observations", "object_types": ["OBSERVATION"],
         "geometry_kinds": ["POINT"]}],
    "timeline": {"include": ["object_version", "alert", "recommendation", "decision", "analyst_action",
                             "association_proposal"]},
    "alert_rules": ["rule-infrastructure-conflict", "rule-reported-disruption", "rule-movement-route-risk",
                    "rule-stale-stock", "rule-source-dependence"],
    "actions": ["ACKNOWLEDGE", "ANNOTATE", "ACCEPT", "REJECT", "DEFER", "ESCALATE"],
    "access": {"min_role": "OBSERVER"},
    "reports": ["json", "markdown", "text"],
}
