"""Curunír V5 epistemic validation and longitudinal research-shadow operations."""

MILESTONE = "CURUNIR_SIX_SURFACE_EPISTEMIC_VALIDATION_AND_LONGITUDINAL_OPERATIONS_V5"
HUMAN_REVIEW_STATE = "HUMAN_REVIEW_PENDING"
MODEL_REVIEW_STATE = "MODEL_PANEL_SECONDARY_REVIEW"

